### ISSUE TITLE
Unable to get working

### ISSUE THREAD

**Issue by adamgibbins** [ayyjayess/beancount-financequote#1]
Hi,
Thanks for publishing this, it looks to solve a big pain point I've had for years.
I'm struggling to get it working per the README however.

I'm throwing the sources into beancount/prices/sources and installing Finance::Quote via CPAN, however when I run the example you give, I get:
```
% bean-price -v -e GBP:financequote/ftfunds:GB00B3X7QG63
INFO    : Using price cache at "/tmp/bean-price.cache" (with indefinite expiration)
INFO    : Processing at date: 2017-07-16
ERROR   : Could not fetch for job: DatedPrice(base='ftfunds:GB00B3X7QG63', quote='GBP', date=None, sources=[PriceSource(module=<module 'beancount.prices.sources.financequote' from '/usr/local/lib/python3.6/site-packages/beancount/prices/sources/financequote.py'>, symbol='ftfunds:GB00B3X7QG63', invert=False)])
```

Running the non-ftfunds example works fine:
```
% bean-price -e USD:financequote/NASDAQ:GOOG
2017-07-14 price NASDAQ:GOOG                        955.99 USD
```

Any clue to what I might be doing wrong?

Thanks

**Comment by vonpupp** [comment]
Is there a way to make this work installing it as a python package?

When I do:
```
pip install git+https://github.com/andyjscott/beancount-financequote
```

And then try it:
```
bean-price -e USD:financequote/NASDAQ:GOOG
```

I get:
```
(.env3) > $ bean-price -e USD:financequote/NASDAQ:GOOG                                                                                                                            
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/beancount/prices/find_prices.py", line 147, in import_source
    __import__(default_name)
ModuleNotFoundError: No module named 'beancount.prices.sources.financequote'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/beancount/prices/find_prices.py", line 151, in import_source
    __import__(module_name)
ModuleNotFoundError: No module named 'financequote'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/bean-price", line 2, in <module>
    from beancount.prices.price import main; main()
  File "/usr/lib/python3.6/site-packages/beancount/prices/price.py", line 310, in main
    args, jobs, entries = process_args()
  File "/usr/lib/python3.6/site-packages/beancount/prices/price.py", line 281, in process_args
    psource_map = find_prices.parse_source_map(source_str)
  File "/usr/lib/python3.6/site-packages/beancount/prices/find_prices.py", line 99, in parse_source_map
    for source_str in source_strs.split(','))
  File "/usr/lib/python3.6/site-packages/beancount/prices/find_prices.py", line 99, in <genexpr>
    for source_str in source_strs.split(','))
  File "/usr/lib/python3.6/site-packages/beancount/prices/find_prices.py", line 124, in parse_single_source
    module = import_source(short_module_name)
  File "/usr/lib/python3.6/site-packages/beancount/prices/find_prices.py", line 155, in import_source
    module_name, exc))
ImportError: Could not find price source module "financequote": No module named 'financequote'
```

I am not sure how the sources scan works out, but I would like to avoid copying up files into beancount dir structure but rather use the package instead.

Thanks.
